# Generated by Django 4.2.1 on 2023-06-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_planpremium_user_premium_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
