# Generated by Django 4.2.1 on 2023-06-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_suscripcion_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='Activo', max_length=32),
        ),
    ]
