# Generated by Django 4.2.1 on 2023-06-04 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
