# Generated by Django 4.2.1 on 2023-06-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_pedido_apellido_receptor_pedido_comuna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='apellido_receptor',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comuna',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombre_receptor',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(max_length=64),
        ),
    ]
