# Generated by Django 4.2.1 on 2023-06-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_pedido_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='apellido_receptor',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comuna',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombre_receptor',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
