# Generated by Django 4.2.1 on 2023-06-12 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_boleta_buy_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.estadopedido'),
        ),
    ]
