# Generated by Django 4.2.1 on 2023-06-30 22:03

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_listadeseados_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars', validators=[users.validators.validate_file_size, users.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='user',
            name='creador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
