# Generated by Django 4.2.1 on 2023-07-01 02:02

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_avatar_user_creador_user_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='avatars', validators=[users.validators.validate_file_size, users.validators.validate_file_extension]),
        ),
    ]
