# Generated by Django 4.2.1 on 2023-07-01 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='fecha_caducidad',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
