# Generated by Django 4.2.1 on 2023-07-04 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_suscripcion_fecha_caducidad_suscripcion_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('desc', models.TextField()),
                ('portada', models.ImageField(upload_to='mangas_comunidad')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MangaTomo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tomo', models.IntegerField()),
                ('desc', models.TextField()),
                ('path', models.CharField(max_length=255)),
                ('portada', models.ImageField(upload_to='')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mangausuario')),
            ],
        ),
    ]
