# Generated by Django 4.2.1 on 2023-07-04 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0006_alter_mangadigital_timestamp'),
        ('users', '0026_remove_mangatomo_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='mangaUsuario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.mangausuario'),
        ),
        migrations.AlterField(
            model_name='review',
            name='manga',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mangas.mangadigital'),
        ),
    ]
