# Generated by Django 4.2.1 on 2023-07-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_review_mangausuario_alter_review_manga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangatomo',
            name='path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
