# Generated by Django 4.2.1 on 2023-07-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_mangatomo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangausuario',
            name='promedio_puntuacion',
            field=models.IntegerField(default=0),
        ),
    ]
