# Generated by Django 4.2.1 on 2023-07-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_mangausuario_promedio_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_caducidad',
            field=models.DateTimeField(null=True),
        ),
    ]
