# Generated by Django 4.2 on 2023-05-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('m_id', models.IntegerField(primary_key=True, serialize=False)),
                ('m_nombre', models.CharField(max_length=64, unique=True)),
                ('m_stock', models.IntegerField()),
                ('m_digital', models.BooleanField(default=False)),
                ('m_portada', models.TextField()),
                ('m_premium', models.BooleanField(default=False)),
            ],
        ),
    ]
