# Generated by Django 4.2 on 2023-05-09 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='m_digital',
            new_name='digital',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='m_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='m_nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='m_portada',
            new_name='portada',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='m_premium',
            new_name='premium',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='m_stock',
            new_name='stock',
        ),
    ]
