# Generated by Django 4.2 on 2023-05-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_m_digital_manga_digital_rename_m_id_manga_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='portada',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
