# Generated by Django 4.2.1 on 2023-07-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='mangas/portadas/default.png', upload_to='tienda/imagen'),
        ),
    ]
