# Generated by Django 4.2 on 2023-05-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_manga_portada_alter_manga_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='precio',
            field=models.IntegerField(default=10000, max_length=64),
        ),
    ]
