# Generated by Django 4.2.1 on 2023-07-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_producto_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='portada',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='mangas/portadas/default.png', upload_to='tienda/imagen'),
        ),
    ]
