# Generated by Django 4.2.1 on 2023-06-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0005_alter_mangadigital_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangadigital',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
