# Generated by Django 4.2.1 on 2023-07-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0006_alter_mangadigital_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangadigital',
            name='promedio_puntuacion',
            field=models.FloatField(default=0),
        ),
    ]
