# Generated by Django 4.2.1 on 2023-07-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0007_mangadigital_promedio_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangadigital',
            name='promedio_puntuacion',
            field=models.IntegerField(default=0),
        ),
    ]
