# Generated by Django 4.2.1 on 2023-07-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0008_alter_mangadigital_promedio_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangadigital',
            name='portada',
            field=models.ImageField(default='mangas/portadas/default.png', upload_to='mangas/portadas'),
        ),
    ]
